### ISSUE TITLE
Kurs-repo har ingen issues

### ISSUE THREAD

**Issue by henrtk** [infodep/git-kurs#1]
Jeg mener det er en god idé å demonstrere issues, en nyttig funksjon i GitHub-repoer, ved å ha en enkel issue til stede fra begynnelsen av. 
Hva synes dere?

**Comment by trondhauklien** [comment]
Enig. 👍 Kan også være interessant å publisere litt oppgaver som issues etter hvert. Da vil man ha mulighet til å lage branches av oppgavene og får en god simulert arbeidsflyt. 🔥
