### ISSUE TITLE
The group task (10 p)

### ISSUE THREAD

**Issue by trondhauklien** [infodep/git-kurs#11]
Opprett en gren (branch) for gruppa di og gi den et passende navn.

Hver person i gruppen gjør deretter følgende:
1. Sjekk ut grenen (branch) dere nettopp opprettet.
2. Gjør endringer i filen groups.md (med gruppenavn og medlemmer).
3. Commit endringene deres til grenen.

Lag til slutt en pull request for å prøve å få endringene deres slått sammen (merget) med hovedgrenen (`main` branch).

(Gruppen får samlet 10 poeng når alle deloppgavene er fullført)

**Comment by MrArddo** [comment]
Doone
